export interface GeneralLedgerMasterData{

     accountNumber: number,
     companyCode: string,
     chartOfAccounts: string,
     accountGroup: string,
     accountType: string,
     reconciliationAccountInput: boolean,
     reconciliationAccountType: string,
     alternativeGLAccount: number,
     shortDescription: string,
     longDescription: string,
     profitAndLossAccount: boolean,
     balanceSheetAccount: boolean,
     accountCurrency: string,
     balancesInLocalCurrency: boolean,
     exchangeRateKey: string,
     taxCategory: string,
     postingWithoutTaxAllowed: boolean,
     openItemManagement: boolean,
     lineItemManagement: boolean,
     blockedForPosting: boolean,
     markedForDeletion: boolean,
     groupAccountNumber: number,
     tradingPartner: string,
     sortKey: string,
     authorizationGroup: string,
     fieldStatusGroup: string,
     postAutomaticallyOnly: boolean,
     relevantToCashFlow: boolean,
     houseBank: string,
     houseBankAccountID: number,
     interestIndicator: boolean,
     interestCalculationFrequency: number,
     lastDateOfInterestCalculation: Date,
     keyDateofLastInterest: Date,
     controllingArea: string,
     costElement: number,
     unitOfMeasure: string,
     businessArea: string,
     valuationGroup: string,
     inflationKey: string,
     toleranceGroup: string,
     planningLevel: string,
     accountManagedinExternalSystem: number,
     supplementAutomaticPostings: boolean,

}
